name: mobileappdev
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  provider: ^6.1.2
  http: ^1.2.2
  grpc: ^4.0.1
  protobuf: ^3.1.0
  flutter_launcher_icons: ^0.14.2
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background/dice_background.jpg

flutter_native_splash:
  color: "#FFD1A6"
  image: assets/background/dice_background.jpg
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill