version: '3.8'

services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    environment:
      - POSTGRES_USER=quarkususer
      - POSTGRES_PASSWORD=quarkuspassword
      - POSTGRES_DB=quarkusdb
    ports:
      - "5432:5432"
    networks:
      - quarkus-network
    volumes:
      - postgres-data-2:/var/lib/postgresql/data-2

networks:
  quarkus-network:
    driver: bridge

volumes:
  postgres-data-2:
