apiVersion: v1
kind: Service
metadata:
  name: quarkus-backend
  labels:
    app: quarkus-backend
spec:
  selector:
    app: quarkus-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
